### PR TITLE
Keys completition added - source manual 2.4 zabbix agent items

### PR DESCRIPTION
**Pull request by jangaraj**

### CODE REVIEW

**Comment by richlv** [comment]
heya, thanks for this :)
but should we add keys that are known not to work, like log[], logrt[] ?

**Comment by jangaraj** [comment]
Yes, I was also thinking about log[], but then you need to move cursor one (two) position back, so user can be able to write parameters straightaway "log[<cursor>]", without changing cursor position by the user manually. Unfortunately I didn't find any function to update cursor position at the moment, so I've choose "log[" version only. And still it's not the best solution, because result is "log[<space><cursor>". It always needs cursor position update.

**Comment by richlv** [comment]
oh, sorry - i meant the fact that we can never query log/logrt keys with zabbix_get :)

**Comment by jangaraj** [comment]
Pull request cancelled - I've new better one.

**Pull request closed without merging**
